[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
clap = { version = "4.5.13", features = ["derive"] }
pretty_env_logger = "0.5.0"
common = { path = "../common" }
